# Generated by Django 3.2.19 on 2023-06-19 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=500, null=True)),
                ('message', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
