# Generated by Django 3.2.19 on 2023-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20230620_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_subject',
            field=models.CharField(max_length=50, null=True, verbose_name='subject'),
        ),
    ]
