# Generated by Django 3.2.19 on 2023-06-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
    ]
