# Generated by Django 3.2.19 on 2023-06-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_rename_review_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
